import SwiftUI

/// ToursLandingView — design preview
/// Source: Figma "Landing Page" (Final Designs · Outbound · Mobile · v2), node 1-2320.
/// States: default (loaded) · loading · empty
/// Generated by the mobile-prototype skill.
///
/// Static visual preview only — no ViewModel, navigation, or networking.
/// All colour / spacing / typography come from EncoreSwiftUiKit design tokens.
/// TODO(dev): the arrow / home / people / status glyphs use SF Symbols as placeholders.
/// Swap to library `EncoreIcon` assets when equivalents are available.
/// See `dev-reference/tours-landing-dev-ref.md`.

// MARK: - Stub model (preview-only)

private struct TourFlow: Identifiable {
    let id = UUID()
    let actionLabel: String   // e.g. "Start"
    let name: String          // e.g. "Outbound" / "Inbound"
    let systemIcon: String    // SF Symbol placeholder
    let accent: Color         // token-driven accent
}

private enum ToursLandingStubs {
    static let userName = "Arnold Schwarzenegger"
    static let teamName = "Atlanta Team"
    static let homebaseName = "Atlanta Homebase"
    static let initials = "AS"

    static let flows: [TourFlow] = [
        TourFlow(actionLabel: "Start", name: "Outbound",
                 systemIcon: "arrow.up.right",
                 accent: Color.encore("Status/OrangeBold")),
        TourFlow(actionLabel: "Start", name: "Inbound",
                 systemIcon: "arrow.down.right",
                 accent: Color.encore("Status/GreenBold")),
    ]
}

// MARK: - Screen

public struct ToursLandingView: View {

    public enum ScreenState {
        case loaded
        case loading
        case empty
    }

    private let state: ScreenState
    private let onSelectFlow: (String) -> Void

    public init(
        state: ScreenState = .loaded,
        onSelectFlow: @escaping (String) -> Void = { _ in }
    ) {
        self.state = state
        self.onSelectFlow = onSelectFlow
    }

    public var body: some View {
        ZStack(alignment: .top) {
            // Full-bleed body background — fills every edge, incl. under the home indicator.
            Color.encore("Grey/50")
                .ignoresSafeArea()

            VStack(spacing: 0) {
                HeaderView()
                content
                Spacer(minLength: 0)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .top)
    }

    @ViewBuilder
    private var content: some View {
        switch state {
        case .loaded:
            ToursSectionView(flows: ToursLandingStubs.flows, onSelectFlow: onSelectFlow)
        case .loading:
            // Same layout, redacted — realistic skeleton while the landing data loads.
            ToursSectionView(flows: ToursLandingStubs.flows, onSelectFlow: { _ in })
                .redacted(reason: .placeholder)
                .disabled(true)
        case .empty:
            EmptyStateView(content: .empty(
                title: "No tours available",
                subtitle: "You don’t have any tours assigned right now. Pull to refresh or check back later.",
                actionLabel: nil,
                action: nil
            ))
        }
    }
}

// MARK: - Header

private struct HeaderView: View {
    var body: some View {
        HStack(alignment: .center, spacing: Spacing.spacing12) {
            VStack(alignment: .leading, spacing: Spacing.spacing6) {
                Text("Hi \(ToursLandingStubs.userName)")
                    .typography(Typography.h6)
                    .foregroundColor(Color.encore("White/white"))
                    .lineLimit(1)
                    .minimumScaleFactor(0.8)

                HStack(spacing: Spacing.spacing4) {
                    Image(systemName: "person.2.fill")
                        .font(.system(size: Spacing.spacing12))
                    Text(ToursLandingStubs.teamName)
                        .typography(Typography.body2)
                    Text("•")
                        .typography(Typography.body2)
                    Image(systemName: "house.fill")
                        .font(.system(size: Spacing.spacing12))
                    Text(ToursLandingStubs.homebaseName)
                        .typography(Typography.body2)
                        .lineLimit(1)
                    Image(systemName: "chevron.down")
                        .font(.system(size: Spacing.spacing8))
                }
                .foregroundColor(Color.encore("Grey/300"))
                .lineLimit(1)
            }

            .frame(maxWidth: .infinity, alignment: .leading)

            AvatarView(initials: ToursLandingStubs.initials)
        }
        .padding(.horizontal, Spacing.spacing16)
        .padding(.vertical, Spacing.spacing16)
        .frame(maxWidth: .infinity, alignment: .leading)
        // Dark header bleeds up under the system status bar (white clock on dark = the design).
        .background(Color.encore("Grey/900").ignoresSafeArea(edges: .top))
    }
}

private struct AvatarView: View {
    let initials: String

    var body: some View {
        ZStack(alignment: .bottomTrailing) {
            Circle()
                .fill(Color.encore("Avatar/Fill"))
                .frame(width: Spacing.spacing40, height: Spacing.spacing40)
                .overlay(
                    Text(initials)
                        .typography(Typography.Avatar.initialsLg)
                        .foregroundColor(Color.encore("White/white"))
                )
            // Online presence dot.
            Circle()
                .fill(Color.encore("Success/Main"))
                .frame(width: Spacing.spacing12, height: Spacing.spacing12)
                .overlay(Circle().stroke(Color.encore("Grey/900"), lineWidth: 2))
        }
    }
}

// MARK: - Tours section

private struct ToursSectionView: View {
    let flows: [TourFlow]
    let onSelectFlow: (String) -> Void

    var body: some View {
        VStack(alignment: .leading, spacing: Spacing.spacing16) {
            Text("Tours")
                .typography(Typography.h6)
                .foregroundColor(Color.encore("Text/Primary"))

            HStack(spacing: Spacing.spacing12) {
                ForEach(flows) { flow in
                    FlowTileView(flow: flow) { onSelectFlow(flow.name) }
                }
                Spacer(minLength: 0)
            }
        }
        .padding(Spacing.spacing16)
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}

private struct FlowTileView: View {
    // Fixed so both tiles are equal width and the longest flow name ("Outbound") fits on one line.
    private let tileWidth: CGFloat = 132

    let flow: TourFlow
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            VStack(alignment: .leading, spacing: Spacing.spacing12) {
                ZStack {
                    RoundedRectangle(cornerRadius: Spacing.spacing8)
                        .fill(flow.accent)
                        .frame(width: Spacing.spacing40, height: Spacing.spacing40)
                    Image(systemName: flow.systemIcon)
                        .font(.system(size: Spacing.spacing20, weight: .bold))
                        .foregroundColor(Color.encore("White/white"))
                }

                VStack(alignment: .leading, spacing: Spacing.spacing2) {
                    Text(flow.actionLabel)
                        .typography(Typography.caption)
                        .foregroundColor(Color.encore("Text/Secondary"))
                    Text(flow.name)
                        .typography(Typography.h6)
                        .foregroundColor(Color.encore("Text/Primary"))
                        .lineLimit(1)
                }
            }
            .padding(Spacing.spacing16)
            .frame(width: tileWidth, alignment: .leading)
            .background(Color.encore("Background/Default"))
            .clipShape(RoundedRectangle(cornerRadius: Spacing.spacing12))
            .shadow(color: Color.black.opacity(0.08),
                    radius: Spacing.spacing8, x: 0, y: Spacing.spacing4)
        }
        .buttonStyle(.plain)
    }
}

// MARK: - Previews

#Preview("Tours Landing — Default") {
    ToursLandingView(state: .loaded)
}

#Preview("Tours Landing — Loading") {
    ToursLandingView(state: .loading)
}

#Preview("Tours Landing — Empty") {
    ToursLandingView(state: .empty)
}
